# Generated by Django 5.0.1 on 2024-09-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department_details',
            new_name='Doctor_details',
        ),
    ]
