# Generated by Django 5.0.1 on 2024-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='departments',
            field=models.ManyToManyField(to='hospital_app.department'),
        ),
    ]
