# Generated by Django 5.0.1 on 2024-09-14 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_doctor_details_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_details',
            name='departments',
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='departments',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.department'),
        ),
    ]
