# Generated by Django 5.0.1 on 2024-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_remove_doctor_details_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='appoinment_count',
            field=models.IntegerField(default=5),
        ),
    ]
