# Generated by Django 5.0.1 on 2024-09-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_rename_appoinment_type_appointment_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctor_details',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctor_details',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctors_image',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctors_image',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
